[book]
authors = ["DingVero"]
language = "zh"
src = "src"
title = "Note of Embedded System"
description = ""

[build]
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/DingWH03/note-embedded"
edit-url-template = "https://github.com/DingWH03/note-embedded/edit/master/{path}"
input-404 = "404.md"
site-url =  "https://note.cxhap.top/Note-of-Embedded-System/"
cname = "note.cxhap.top"

[output.html.fold]
enable = true
level = 1